backend:
  name: github
  repo: bertho-web/bookandshop
  branch: main
  base_url: https://solitary-brook-f7b6.bertho.workers.dev
  auth_endpoint: /auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test"
    folder: "_test"
    create: true
    fields:
      - label: "Titre"
        name: "title"
        widget: "string"